import { Command } from "commander";
import { greet } from "./commands/greet";

const program = new Command();

program
  .name("oneword-app")
  .description("Command-line tool generated by OneWord")
  .version("1.0.0");

program
  .command("greet")
  .description("Greet someone by name")
  .argument("<name>", "who to greet")
  .option("--shout", "print the greeting in upper case")
  .action((name: string, options: { shout?: boolean }) => {
    const message = greet(name);
    console.log(options.shout ? message.toUpperCase() : message);
  });

program.parse(process.argv);
